version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: docker/services/web/Dockerfile
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: development