version: '3.8'
services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'

  jakdojade_web:
    build:
      context: .
      dockerfile: docker/services/web/Dockerfile
    depends_on:
      - 'db'
    ports:
      - "8000:5000"
    environment:
      FLASK_ENV: development
